# syntax=docker/dockerfile:1

FROM python:3.13 as builder

RUN mkdir /app

ADD backend/ /app

COPY pyproject.toml uv.lock .python-version /app

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# install uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh

RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH"

# install dependencies
RUN uv sync --locked

EXPOSE 8000

CMD ["uv", "run", "bash", "run.sh"]
