FROM python:3.13

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

ADD https://astral.sh/uv/install.sh /uv-installer.sh

RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH"

RUN uv sync --locked

WORKDIR backend

CMD ["uv", "run", "bash", "run.sh"]
