[project]
name = "feed-this-much"
version = "0.1.0"
description = "II1305 project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.7",
    "gunicorn>=23.0.0",
    "ruff>=0.11.2",
]
