name: "lint-python"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, linux, ARM64] 
    steps:
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
					pip install ruff
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --output-format=github .
